### ISSUE TITLE
An action could not be made for `handleInput`.

### ISSUE THREAD

**Issue by henderikus** [cibernox/ember-power-select-typeahead#13]
Hi Folks,

I have installed ember-power-select-typeahead version 0.3.8, but am getting the following error while try to use it:

> ember.debug.js:16582 Uncaught Error: An action could not be made for `handleInput` in <webapp@component:power-select-typeahead/trigger::ember1171>. Please confirm that you are using either a quoted action name (i.e. `(action 'handleInput')`) or a function available in <webapp@component:power-select-typeahead/trigger::ember1171>.

Any suggestions what it could be?

Cheers!

**Comment by cibernox** [comment]
@henderikus what version of Ember Power Select do you have?

**Comment by henderikus** [comment]
Not the right one ;-)  After upgrading ember-power-select to 0.10.10 from 0.9.3 the problem is solved.

Thanks for the reminder.

**Comment by cibernox** [comment]
👍
