### ISSUE TITLE
Update to EPS 1.0.0-alpha

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select-typeahead#14]

**Comment by tyronepost** [comment]
Hi,

In my current project I'm doing some work with ember 2.8 beta:

 Ember  : 2.8.0-beta.2
 jQuery : 3.1.0

with the latest version of EPS.  To get this addon to work I pulled in @jesseditson 's beta_refactor branch

https://github.com/jesseditson/ember-power-select-typeahead/tree/beta_refactor

**Comment by cibernox** [comment]
I need to revisit this addon and finish the update. 

However, there is a know issue in ember 2.8 beta that breaks Ember Power Select and other addons, so be aware that it might break: https://github.com/emberjs/ember.js/issues/13846

**Comment by cibernox** [comment]
I've just released 0.4.0 that works with the latest 1.0.0-beta. Try and check if it works.

**Comment by tyronepost** [comment]
I think I found a bug, but maybe I'm using the add on incorrectly.  Basically what's happening is when I enter a value or select it from the rendered dropdown, the value is rendered twice, once in the input, and once within the enclosing div tag.

[recreation here](https://github.com/tyronepost/power-select-typeahead-doublerender)

**Comment by cibernox** [comment]
@tyronepost No, you didn't do anything wrong. I forgot one extra `{{text}}` in a template that I added while debugging. 

Update to 0.4.2.

My bad!
