### ISSUE TITLE
Concatenated CSS classes are not propagating

### ISSUE THREAD

**Issue by christophersansone** [cibernox/ember-power-select-typeahead#21]
In the Javascript, the CSS class CPs are named `concatenatedTriggerClasses` and `concatenatedDropdownClasses`.  However, in the Handlebars file, they are being referenced as `concatenatedTriggerClass` and `concatenatedDropdownClass`.  As a result, setting `triggerClass` on `{{power-select-typeahead}}` does not work.

**Comment by cibernox** [comment]
Fixed now. I was on holidays and then I just forgot about this.
