### ISSUE TITLE
link to the demo source code

### ISSUE THREAD

**Issue by jameslaneconkling** [cibernox/ember-power-select-typeahead#26]
or include in the repo?

Would be very helpful as a quick how-to.

**Comment by cibernox** [comment]
It is already in the repo. Inside the dummy app. The demo page is just this repo, deployed

**Comment by jameslaneconkling** [comment]
ah, at [tests/dummy](https://github.com/cibernox/ember-power-select-typeahead/tree/master/tests/dummy).  Thanks for that.
