### ISSUE TITLE
Using labelPath can cause "undefined" to appear

### ISSUE THREAD

**Issue by TopsyCM** [cibernox/ember-power-select-typeahead#38]
Repro on the [demo](https://ember-power-select-typeahead.pagefrontapp.com/):
1. In the third demo, "Typeahead with non-async search", type a letter so that the select options appear.
2. Click elsewhere on the page to defocus the typeahead input.

Result: The input value changes to "undefined".

Expected behavior: The input value remains blank and shows the placeholder.

Explanation/rambling: The component attempts to access the labelPath property of the selected value when the selected value is null.

**Comment by cibernox** [comment]
Labeled as a bug, it should be easy to fix.
