### ISSUE TITLE
Pressing escape clears the input without clearing the selection

### ISSUE THREAD

**Issue by TopsyCM** [cibernox/ember-power-select-typeahead#39]
Repro on the [demo](https://ember-power-select-typeahead.pagefrontapp.com/)
1. Make a selection in one of the sample components.
2. Click in that input to give it focus.
3. Press escape.

Result: The text area loses focus and is cleared. However, the selected value is still assigned. This is not obvious on the demo page because there is nothing using the selected value, but it can be verified with the inspector. In uses where the selected value is used (to enable a button, for example), this is confusing.

Expected Behavior: One of the following:
1. The selected value is shown.
2. The text area is cleared and the selected value is cleared.
I'm guessing that option 1 is more appropriate since 'allowClear' is a separate setting.

**Comment by cibernox** [comment]
@TopsyCM both this and #38 should be fixed in the lastest version.

**Comment by TopsyCM** [comment]
Groovy! Thanks.
