### ISSUE TITLE
No on-screen keyboard in mobile

### ISSUE THREAD

**Issue by TopsyCM** [cibernox/ember-power-select-typeahead#42]
Touching an epst component in a mobile device causes a single item to appear underneath "Type to search". The on-screen keyboard does not appear. Sometimes it is possible to focus the text input and get the keyboard, but I haven't been able to figure out exactly what I have to do to get that to happen.

Is there some event handling that I need to be manually or is something broken?

**Comment by cibernox** [comment]
I don't know what might be going on. The trigger just has a `<input type="text">. Why would it not open the keyboard?

**Comment by TopsyCM** [comment]
No idea so far, but it happens in the demo as well as my app. The ember-power-select examples in the docs work as expected, but something is different with -typeahead.

**Comment by cibernox** [comment]
I can reproduce it. I labeled this as a bug and I'll try to find it tomorrow 💤

**Comment by TopsyCM** [comment]
Have you made any progress on identifying the cause of this bug? Is there anything I can do to help? This is a blocking issue for us.

**Comment by cibernox** [comment]
No, life got in the middle, but I'll check it this weekend.

**Comment by TopsyCM** [comment]
I see that the listener added by the basic-dropdown trigger is intercepting touch events. I don't understand how all the pieces fit together yet, so I that's as far as I've gotten.
https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js#L158-L161

**Comment by cibernox** [comment]
That is good info actually. I have a suspect now.

**Comment by TopsyCM** [comment]
Yes, that seems to have fixed it.

**Comment by cibernox** [comment]
Great. Closing.
