### ISSUE TITLE
Is there a way to manually trigger search async action?

### ISSUE THREAD

**Issue by tevch** [cibernox/ember-power-select-typeahead#43]
I have the component functioning pretty well.
what i need in addition is to put some value in the control( this i can do with Ember.$('.ember-power-select-search-input').val('amazon');)

i also need to trigger search and display autocomplete list - this i couldn't find a way how to do it

I would appreciate any tips

Thank you

**Comment by cibernox** [comment]
You just need to trigger an `input` event on the text field.

On modern browsers you can:
```js
let $input = $('ember-power-select-input');
$input.val('amazon');
$input.get(0).dispatchEvent(new Event('input'));
```

In old versions of IE creating an event needs a bit more ceremony, but it's not hard either.
