### ISSUE TITLE
triggerId not supported

### ISSUE THREAD

**Issue by denchen** [cibernox/ember-power-select-typeahead#48]
It seems `triggerId` isn't supported. I tried to pass it into `ember-power-select-typeahead`, but the ID doesn't get attached to the Ember Power Select element. Looking at https://github.com/cibernox/ember-power-select-typeahead/blob/master/addon/templates/components/power-select-typeahead.hbs, it seems `triggerId` is not one of the attributes you pass in.

**Comment by cibernox** [comment]
You're right. Could you create a PR for that forwarding it to EPS?
