### ISSUE TITLE
Provide more complete example

### ISSUE THREAD

**Issue by brandonparsons** [cibernox/ember-power-select-typeahead#5]
Would it be possible to put a bit more detail into how this is supposed to be used?

i.e. What should `searchAsync` be returning in the README?

**Comment by cibernox** [comment]
This component is an addon over ember-power-select. 99% of de docs in www.ember-power-select.com also apply to this component.

**Comment by brandonparsons** [comment]
Gotcha - I wasn't aware of the `search` functionality on power-select until I read the docs a bit more. Good work!
