### ISSUE TITLE
Debounce keystrokes?

### ISSUE THREAD

**Issue by adambedford** [cibernox/ember-power-select-typeahead#55]
Is it possible to debounce while typing into the search field and/or add a minimum text length before making a network request?

**Comment by scottwernervt** [comment]
Check out [Ember Power Select Docs > Debounce searches](http://www.ember-power-select.com/cookbook/debounce-searches). Add a conditional statement that checks the term length and returns an empty array if minimum not met.

**Comment by adambedford** [comment]
Thank you for pointing me in the right direction!
