### ISSUE TITLE
[HELP REQUEST] TypeError: Cannot read property 'vPosition' of undefined

### ISSUE THREAD

**Issue by mqje** [cibernox/ember-power-select-typeahead#60]
Sorry for to reopen that, but I just figured out why I add this error. Basically, I receive this error when I am typing in my ember-power-select-typeahead, and this error come from the 
`renderInPlace=true`  in my component.

my components look like : 
```
{{#power-select-typeahead
                search=(action 'findAll')
                selected=selected.name
                renderInPlace=true
                onchange=(action (mut selected))
        as |result|}}
            {{result.name}}
            <span style="color: #919bb3;font-style: italic; text-align: right">{{t result.type}}</span>
        {{/power-select-typeahead}}
```

and my component is called here :
```
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        {{global-search label=(t 'search')}}
      </li>
      * * *
     </ul>
  </div>
</div>
```
 Maybe somebody know why I receive this.

**Comment by snewcomer** [comment]
@mqje can you post a stacktrace?  I'm curious if it is coming from `power-select` (from which this component is based) rather than `power-select-typeahead`.

**Comment by mqje** [comment]
This is the error I received:
![stactrace](https://user-images.githubusercontent.com/26004843/30533553-21695a68-9c5a-11e7-8f02-fc16f1489180.png)

And this is the line 212 of content.js: 
![stacktrace2](https://user-images.githubusercontent.com/26004843/30533564-3592bb60-9c5a-11e7-9da0-75433ccaf4f7.png)

I'm not really sure what a stacktrace is, so tell me if you need more!

**Comment by snewcomer** [comment]
@mqje this is related to [ember-basic-dropdown](https://github.com/cibernox/ember-basic-dropdown/blob/84ebf0fc73dc7e168836b20dd76aca99785f3988/addon/components/basic-dropdown/content.js).  What version of `ember-power-select` are you on?  What happens when `renderInPlace` is false?

**Comment by mqje** [comment]
@snewcomer I am on `"ember-power-select": "1.9.6"`. When `renderIsFalse=false`, the dropdown is hidden behind a the elements of my `<ul>`. Maybe there is an other way around, but I don't really know.

**Comment by snewcomer** [comment]
@mqje You are correct.  I'll try to see if I can help in a PR this morning.

**Comment by snewcomer** [comment]
@mqje this branch I believe fixes it for you.

**Comment by mqje** [comment]
With the release of ember-power-select-typeahead@0.6.0, this issue is fixed.
