### ISSUE TITLE
Is this usable at all yet?

### ISSUE THREAD

**Issue by robclancy** [cibernox/ember-power-select-typeahead#7]

**Comment by cibernox** [comment]
I use it. I haven't put a ton of engineering on it, but it it works for my use case.

**Comment by robclancy** [comment]
I got it working, had to do some hacky things here and there and override most templates for some extra stuff I needed. Will be making a bunch of pull requests when I get a chance.

**Comment by cibernox** [comment]
All things said, given that ember-power-select is a bit in flux yes (not that much the public API, but the parameters that the individual components receive) I haven't put much love on it.

It will probably need a couple small tweaks to work with 0.9.0
