### ISSUE TITLE
bump dependencies (ember-power-select@2.0.9)

### ISSUE THREAD

**Issue by theseyi** [cibernox/ember-power-select-typeahead#78]
now that `ember-power-select@2.0.9` has been released, can this be updated as well? I use both `ember-power-select@2.0.9` and `ember-power-select-typeahead@0.7.2` -> `ember-power-select-typeahead@2.0.5` in my application and having two versions of ember-power-select loaded fails my dependency lint test

**Comment by cibernox** [comment]
Sure, you can update the dependency. Although the dependency on this repo use a `^`, any version bigger than 2.0.0-beta.5 should work, and your app shouldn't have two copies. 
I think that if you remove your lockfile and reinstall you'll have only one.
